{
 "title": "MK - Fleet Links",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster_id",
    "label": "Cluster ID",
    "query": "label_values(console_url, cluster_id)"
   }
  ]
 },
 "panels": [
  {
   "title": "OpenShift Cluster Versions & Age",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "cluster_version{cluster_id=~\"$cluster_id\",type=\"cluster\"} * on(cluster_id) group_left(url) console_url"
    }
   ]
  },
  {
   "title": "Kafka CRs per OpenShift Cluster",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": " sum(strimzi_resources{cluster_id=~\"$cluster_id\",kind=~\"Kafka\"}) by(cluster_id) * on(cluster_id) group_right() console_url "
    }
   ]
  },
  {
   "title": "Namespace age per Kafka Cluster",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "label_replace(kube_namespace_created{cluster_id=~\"$cluster_id\"}, 'resource_namespace', '$1', 'namespace', '(.*)') * on(resource_namespace) group_left(cluster_id) strimzi_resource_state{cluster_id=~\"$cluster_id\"}"
    }
   ]
  },
  {
   "title": "Kafka CRs (Ready)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "(strimzi_resource_state{cluster_id=~\"$cluster_id\",kind=\"Kafka\"} == 1) + on(cluster_id) group_left(url) console_url"
    }
   ]
  },
  {
   "title": "Kafka CRs (Not Ready)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "(strimzi_resource_state{cluster_id=~\"$cluster_id\",kind=\"Kafka\"} != 1) + on(cluster_id) group_left(url) console_url"
    }
   ]
  }
 ]
}