{
 "title": "MK - Fleet Load",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "OSD Cluster Count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "OSD Cluster Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(cluster_version{type=\"current\"})",
     "legendFormat": "Total # OSD Clusters"
    }
   ]
  },
  {
   "title": "OSD Cluster Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(cluster_version{type=\"current\"}) or vector(0)"
    }
   ]
  },
  { "title": "Kafka Instance Count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Kafka Instance Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(strimzi_resource_state{kind=\"Kafka\"} == 1)",
     "legendFormat": "Total # Kafka Clusters Ready"
    },
    {
     "expr": "sum(strimzi_resources{kind=~\"Kafka\"})",
     "legendFormat": "Total # Kafka Clusters Requested"
    }
   ]
  },
  {
   "title": "Kafka Instances Ready",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(strimzi_resource_state{kind=~\"Kafka\"} == 1) or vector(0)"
    }
   ]
  },
  {
   "title": "Kafka Instances Requested",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(strimzi_resources{kind=~\"Kafka\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Kafka Instance Count by OSD Cluster",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(count(strimzi_resource_state{kind=\"Kafka\"} == 1) by(cluster_id), \"glabel\", \"$1 ready\", \"cluster_id\", \"(.*)\")",
     "legendFormat": "{{glabel}}"
    },
    {
     "expr": "label_replace(sum(strimzi_resources{kind=~\"Kafka\"}) by(cluster_id), \"glabel\", \"$1 requests\", \"cluster_id\", \"(.*)\")",
     "legendFormat": "{{glabel}}"
    }
   ]
  },
  {
   "title": "Kafka CRs by OSD Cluster",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 14 },
   "targets": [
    {
     "expr": "sum(strimzi_resources{kind=~\"Kafka\"} * on(cluster_id) group_left(url) console_url) by(cluster_id, url)"
    }
   ]
  },
  {
   "title": "AddOn Operator Versions count across OSD Clusters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }
  },
  {
   "title": "AddOn Operator Versions count across OSD clusters",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(subscription_sync_total{installed=~\"kas-fleetshard.*|observability-operator.*|strimzi.*\"})  by (installed)",
     "legendFormat": "{{installed}}"
    }
   ]
  },
  {
   "title": "AddOn Operator Version count across OSD Clusters",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 21 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(subscription_sync_total{installed=~\"kas-fleetshard.*|observability-operator.*|strimzi.*\"})  by (installed)",
     "legendFormat": "{{installed}}"
    }
   ]
  },
  { "title": "Firing Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Count of alerts firing by severity and alertname",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\", alertname!=\"DeadMansSwitch\"} * on(cluster_id) group_left(url) console_url) by(severity, alertname, cluster_id, url)"
    }
   ]
  },
  {
   "title": "Total Criticals Firing",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\",severity=\"critical\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Total Warnings Firing",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\",severity=\"warning\"}) or vector(0)"
    }
   ]
  }
 ]
}